// Rótulos de EXIBIÇÃO em inglês pros presets do catálogo do plugin SketchUp
// (i18n EN do painel). O VALOR enviado à API continua sendo a string pt-BR —
// este mapa é só display. Cobertura conferida contra lib/prompts.ts em
// 2026-09-01; preset sem entrada cai no pt-BR (fallback seguro).

export const PRESET_LABELS_EN: Record<string, string> = {
  // ── Segmentos (interior + exterior) ─────────────────────────────────────────
  'Residencial': 'Residential',
  'Corporativo': 'Corporate',
  'Comercial': 'Commercial',
  'Gastronomia': 'Food & beverage',
  'Hospitalidade': 'Hospitality',
  'Saúde': 'Healthcare',
  'Educação': 'Education',
  'Institucional': 'Institutional',
  'Paisagismo': 'Landscaping',

  // ── Ambientes internos ──────────────────────────────────────────────────────
  'Sala de Estar': 'Living room',
  'Sala de Jantar': 'Dining room',
  'Cozinha': 'Kitchen',
  'Cozinha Gourmet': 'Gourmet kitchen',
  'Suíte Master': 'Master suite',
  'Quarto': 'Bedroom',
  'Quarto Infantil': "Kids' bedroom",
  'Banheiro': 'Bathroom',
  'Lavabo': 'Powder room',
  'Home Office': 'Home office',
  'Área de Serviço': 'Laundry room',
  'Varanda Gourmet': 'Gourmet balcony',
  'Closet': 'Walk-in closet',
  'Hall de Entrada': 'Entry hall',
  'Área de Lazer': 'Leisure area',
  'Escritório Corporativo': 'Corporate office',
  'Open Space': 'Open space',
  'Sala de Reunião': 'Meeting room',
  'Sala de Diretoria': 'Boardroom',
  'Recepção Corporativa': 'Corporate reception',
  'Coworking': 'Coworking',
  'Escritório Privativo': 'Private office',
  'Sala de Treinamento': 'Training room',
  'Lounge Corporativo': 'Corporate lounge',
  'Copa / Descompressão': 'Pantry / break room',
  'Auditório': 'Auditorium',
  'Espaço Colaborativo': 'Collaborative space',
  'Work Café': 'Work café',
  'Loja em Shopping': 'Mall store',
  'Loja de Rua': 'Street-front store',
  'Showroom': 'Showroom',
  'Boutique': 'Boutique',
  'Loja de Moda': 'Fashion store',
  'Loja de Decoração': 'Home decor store',
  'Loja de Tecnologia': 'Tech store',
  'Quiosque': 'Kiosk',
  'Espaço de Atendimento': 'Customer service area',
  'Recepção Comercial': 'Retail reception',
  'Stand de Vendas': 'Sales stand',
  'Vitrine Interna': 'In-store display window',
  'Restaurante': 'Restaurant',
  'Restaurante Premium': 'Upscale restaurant',
  'Café': 'Café',
  'Cafeteria': 'Coffee shop',
  'Bistrô': 'Bistro',
  'Bar': 'Bar',
  'Wine Bar': 'Wine bar',
  'Padaria': 'Bakery',
  'Hamburgueria': 'Burger joint',
  'Praça de Alimentação': 'Food court',
  'Cozinha Aberta': 'Open kitchen',
  'Balcão de Atendimento': 'Service counter',
  'Lobby de Hotel': 'Hotel lobby',
  'Recepção de Hotel': 'Hotel reception',
  'Quarto de Hotel': 'Hotel room',
  'Suíte de Hotel': 'Hotel suite',
  'Lounge': 'Lounge',
  'Rooftop': 'Rooftop',
  'Área de Café da Manhã': 'Breakfast area',
  'Spa': 'Spa',
  'Corredor de Hotel': 'Hotel corridor',
  'Sala de Espera Premium': 'Upscale waiting room',
  'Consultório': 'Consulting room',
  'Clínica': 'Clinic',
  'Recepção de Clínica': 'Clinic reception',
  'Sala de Espera': 'Waiting room',
  'Consultório Odontológico': 'Dental office',
  'Consultório Médico': "Doctor's office",
  'Sala de Exames': 'Exam room',
  'Sala de Atendimento': 'Treatment room',
  'Espaço de Bem-Estar': 'Wellness space',
  'Sala de Aula': 'Classroom',
  'Biblioteca': 'Library',
  'Recepção Educacional': 'School reception',
  'Área de Estudo': 'Study area',
  'Lounge Estudantil': 'Student lounge',
  'Laboratório': 'Laboratory',
  'Espaço Infantil Educacional': "Children's learning space",

  // ── Ambientes externos ──────────────────────────────────────────────────────
  'Fachada Residencial': 'Residential facade',
  'Casa Térrea': 'Single-story house',
  'Sobrado': 'Two-story house',
  'Casa Contemporânea': 'Contemporary house',
  'Casa em Condomínio': 'Gated community house',
  'Edifício Residencial': 'Residential building',
  'Área de Piscina': 'Pool area',
  'Jardim Residencial': 'Residential garden',
  'Entrada Principal': 'Main entrance',
  'Fachada de Loja': 'Store facade',
  'Galeria Comercial': 'Shopping arcade',
  'Showroom Externo': 'Outdoor showroom',
  'Restaurante Externo': 'Outdoor restaurant',
  'Café Externo': 'Outdoor café',
  'Fachada com Vitrine': 'Facade with display window',
  'Stand Comercial': 'Commercial stand',
  'Fachada Corporativa': 'Corporate facade',
  'Prédio Comercial': 'Commercial building',
  'Edifício Corporativo': 'Corporate tower',
  'Entrada Empresarial': 'Business entrance',
  'Sede Corporativa': 'Corporate headquarters',
  'Complexo Empresarial': 'Business complex',
  'Coworking Externo': 'Outdoor coworking',
  'Pátio Corporativo': 'Corporate courtyard',
  'Fachada de Hotel': 'Hotel facade',
  'Entrada de Hotel': 'Hotel entrance',
  'Resort': 'Resort',
  'Pousada': 'Guesthouse',
  'Área de Piscina de Hotel': 'Hotel pool area',
  'Lounge Externo': 'Outdoor lounge',
  'Terraço': 'Terrace',
  'Escola': 'School',
  'Universidade': 'University',
  'Hospital': 'Hospital',
  'Centro Cultural': 'Cultural center',
  'Edifício Público': 'Public building',
  'Espaço Comunitário': 'Community space',
  'Jardim Contemporâneo': 'Contemporary garden',
  'Praça': 'Plaza',
  'Parque Urbano': 'Urban park',
  'Pátio Interno': 'Inner courtyard',
  'Jardim Sensorial': 'Sensory garden',
  'Área de Convivência': 'Communal area',
  'Paisagismo Residencial': 'Residential landscaping',
  'Paisagismo Comercial': 'Commercial landscaping',

  // ── Iluminação interna ──────────────────────────────────────────────────────
  'Preservar Original': 'Keep original',
  'Clara e Natural': 'Bright & natural',
  'Natural Suave': 'Soft natural',
  'Luz de Janela': 'Window light',
  'Nublado': 'Overcast',
  'Quente e Aconchegante': 'Warm & cozy',
  'Entardecer Quente': 'Warm dusk',
  'Noturna Aconchegante': 'Cozy night',
  'Sofisticada e Cênica': 'Sophisticated & dramatic',
  'Corporativa Neutra': 'Neutral corporate',
  'Natural Profissional': 'Professional natural',
  'Luz Difusa Uniforme': 'Even diffused light',
  'Escritório Contemporâneo': 'Contemporary office',
  'Iluminação Técnica': 'Technical lighting',
  'Noturna Executiva': 'Executive night',
  'Clara e Produtiva': 'Bright & productive',
  'Comercial Bem Iluminada': 'Bright retail',
  'Varejo Premium': 'Premium retail',
  'Showroom Iluminado': 'Lit showroom',
  'Destaque de Produto': 'Product highlight',
  'Iluminação de Loja': 'Store lighting',
  'Noturna Comercial': 'Retail night',
  'Luz de Vitrine': 'Display window light',
  'Cênica e Intimista': 'Dramatic & intimate',
  'Noturna Sofisticada': 'Sophisticated night',
  'Café com Luz Natural': 'Daylit café',
  'Luz Baixa Decorativa': 'Low decorative light',
  'Premium Aconchegante': 'Cozy premium',
  'Luz Natural Elegante': 'Elegant natural light',
  'Noturna Refinada': 'Refined night',
  'Spa Relaxante': 'Relaxing spa',
  'Lobby Iluminado': 'Lit lobby',
  'Entardecer de Hotel': 'Hotel dusk',
  'Clara e Limpa': 'Bright & clean',
  'Clínica Neutra': 'Neutral clinical',
  'Luz Difusa Suave': 'Soft diffused light',
  'Iluminação Profissional': 'Professional lighting',
  'Aconchegante e Calma': 'Cozy & calm',
  'Saúde Premium': 'Premium healthcare',
  'Clara e Funcional': 'Bright & functional',
  'Luz Difusa': 'Diffused light',
  'Ambiente Produtivo': 'Productive ambience',
  'Biblioteca Aconchegante': 'Cozy library',
  'Sala Bem Iluminada': 'Well-lit room',

  // ── Iluminação externa ──────────────────────────────────────────────────────
  'Diurno': 'Daytime',
  'Entardecer': 'Dusk',
  'Golden Hour': 'Golden hour',
  'Blue Hour': 'Blue hour',
  'Noturno Iluminado': 'Lit night',
  'Chuva Leve': 'Light rain',
  'Diurno Comercial': 'Commercial daytime',
  'Fachada Bem Iluminada': 'Well-lit facade',
  'Vitrine Noturna': 'Night display window',
  'Noturno Comercial': 'Commercial night',
  'Shopping Atmosphere': 'Mall atmosphere',
  'Diurno Corporativo': 'Corporate daytime',
  'Fachada Profissional': 'Professional facade',
  'Noturno Executivo': 'Executive night',
  'Luz Urbana': 'Urban light',
  'Nublado Sofisticado': 'Sophisticated overcast',
  'Entardecer Premium': 'Premium dusk',
  'Noturno Refinado': 'Refined night',
  'Resort Diurno': 'Daytime resort',
  'Luz de Piscina': 'Pool light',
  'Atmosfera Tropical': 'Tropical atmosphere',
  'Diurno Claro': 'Bright daytime',
  'Nublado Suave': 'Soft overcast',
  'Luz Natural': 'Natural light',
  'Iluminação Urbana': 'Urban lighting',
  'Noturno Institucional': 'Institutional night',
  'Diurno Natural': 'Natural daytime',
  'Entardecer Suave': 'Soft dusk',
  'Luz Filtrada': 'Filtered light',
  'Noturno Paisagístico': 'Landscape night',

  // ── Entornos externos ───────────────────────────────────────────────────────
  'Entorno Neutro': 'Neutral surroundings',
  'Rua Arborizada': 'Tree-lined street',
  'Condomínio': 'Gated community',
  'Bairro Nobre': 'Upscale neighborhood',
  'Zona Urbana': 'Urban area',
  'Zona Rural': 'Rural area',
  'Beira-Mar': 'Seafront',
  'Beira-Rio': 'Riverfront',
  'Serra': 'Mountains',
  'Praça Urbana': 'City square',
  'Jardim': 'Garden',
  'Estacionamento': 'Parking lot',
  'Calçada Comercial': 'Commercial sidewalk',

  // ── Contextos internos ──────────────────────────────────────────────────────
  'Clean / Neutro': 'Clean / neutral',
  'Premium': 'Premium',
  'Urbano': 'Urban',
  'Natural': 'Natural',
  'Minimalista': 'Minimalist',
  'Aconchegante': 'Cozy',

  // ── Elementos de cena ───────────────────────────────────────────────────────
  'Decoração': 'Decor',
  'Pessoas': 'People',
  'Vegetação': 'Greenery',
  'Luzes Acesas': 'Lights on',
  'Raios de Sol': 'Sun rays',
  'Pessoas Trabalhando': 'People working',
  'Computadores': 'Computers',
  'Mesas de Trabalho': 'Workstations',
  'Branding Sutil': 'Subtle branding',
  'Divisórias de Vidro': 'Glass partitions',
  'Vegetação Interna': 'Indoor plants',
  'Luminárias Técnicas': 'Technical light fixtures',
  'Telas / Monitores': 'Screens / monitors',
  'Clientes': 'Customers',
  'Funcionários': 'Staff',
  'Produto em Destaque': 'Featured product',
  'Expositores': 'Display stands',
  'Vitrine': 'Display window',
  'Letreiro': 'Sign',
  'Displays': 'Displays',
  'Clientes Sentados': 'Seated customers',
  'Garçons': 'Waiters',
  'Mesas Postas': 'Set tables',
  'Balcão': 'Counter',
  'Luminárias Decorativas': 'Decorative light fixtures',
  'Cozinha Aparente': 'Exposed kitchen',
  'Pratos / Bebidas': 'Dishes / drinks',
  'Decoração Premium': 'Premium decor',
  'Obras de Arte': 'Artwork',
  'Mobiliário Sofisticado': 'Sophisticated furniture',
  'Recepção': 'Reception',
  'Malas / Bagagens': 'Luggage',
  'Pessoas Aguardando': 'People waiting',
  'Poltronas': 'Armchairs',
  'Sinalização': 'Signage',
  'Iluminação Suave': 'Soft lighting',
  'Equipamentos Discretos': 'Discreet equipment',
  'Estudantes': 'Students',
  'Mesas de Estudo': 'Study desks',
  'Livros': 'Books',
  'Quadros': 'Whiteboards',
  'Mobiliário Escolar': 'School furniture',
  'Carros': 'Cars',
  'Calçada': 'Sidewalk',
  'Mobiliário Urbano': 'Street furniture',
  'Árvores': 'Trees',
  'Bancos': 'Benches',
  'Caminhos': 'Paths',
  'Iluminação Externa': 'Outdoor lighting',
  "Água / Espelho d'água": 'Water / reflecting pool',
}
