-- 20260717120000_nodi_assistant.sql
--
-- Nodi (assistente da plataforma) — V1: chamados de suporte + telemetria.
--
-- nodi_tickets: chamado estruturado gerado pelo fluxo "Estou com um problema".
--   O usuário cria e consulta somente os próprios chamados (RLS). Mudança de
--   status/priority é operação de suporte — feita via service_role (não há
--   policy de UPDATE para authenticated de propósito).
--
-- nodi_events: telemetria mínima do assistente, SEM conteúdo livre — nunca
--   gravamos o texto da pergunta ou da conversa, apenas evento + rota + módulo
--   + ids/slugs (política registrada em docs/NODI.md). Deny-all para o browser;
--   só as rotas do servidor escrevem (admin client), no modelo do rate_limits.
--
-- Aditivo e seguro de aplicar; o app tolera as tabelas ausentes (o serviço de
-- chamados devolve erro amigável e a telemetria é fire-and-forget).

-- ── Chamados ──────────────────────────────────────────────────────────────────

create table if not exists public.nodi_tickets (
  id             uuid        primary key default gen_random_uuid(),
  -- Protocolo humano exibido ao usuário/suporte: "ND-<seq>" (ex.: ND-42).
  seq            bigint      generated by default as identity unique,
  user_id        uuid        not null references auth.users (id) on delete cascade,
  status         text        not null default 'open'
                             check (status in ('open', 'in_review', 'resolved', 'closed')),
  -- Prioridade SUGERIDA pelo diagnóstico; o suporte pode reclassificar.
  priority       text        not null default 'normal'
                             check (priority in ('low', 'normal', 'high', 'urgent')),
  category       text        not null default 'other'
                             check (category in (
                               'generation_failed',  -- geração com erro
                               'unexpected_result',  -- saiu, mas diferente do esperado
                               'billing',            -- nodes, cobrança, plano
                               'access',             -- login, conta, equipe
                               'question',           -- dúvida sem resposta segura
                               'other'
                             )),
  title          text        not null check (char_length(title) between 1 and 200),
  description    text        not null check (char_length(description) <= 4000),
  steps_tried    text        check (char_length(steps_tried) <= 2000),
  probable_cause text        check (char_length(probable_cause) <= 1000),
  -- Contexto técnico coletado com consentimento (rota, módulo, engine, status,
  -- erro já REDIGIDO no servidor, navegador/SO, horário). Nunca contém chave,
  -- token, env ou dado de outro usuário — a redação acontece antes do insert.
  context        jsonb       not null default '{}'::jsonb,
  -- Transcrição RESUMIDA da conversa que originou o chamado: [{role, text}].
  -- Enviada só após o usuário revisar e confirmar o resumo.
  transcript     jsonb,
  -- Geração relacionada, quando o problema aponta para uma (id + origem).
  generation_kind text       check (generation_kind in ('render', 'edit', 'video', 'upscale', 'vista')),
  generation_id  text,
  created_at     timestamptz not null default now(),
  -- Sem trigger: o suporte atualiza via service_role e grava updated_at junto.
  updated_at     timestamptz not null default now()
);

comment on table public.nodi_tickets is
  'Chamados de suporte gerados pelo Nodi (assistente). Usuário vê/cria só os próprios; triagem via service_role.';
comment on column public.nodi_tickets.seq is
  'Sequencial do protocolo exibido ao usuário: ND-<seq>.';
comment on column public.nodi_tickets.context is
  'Contexto técnico redigido no servidor (sem chaves/tokens/stack sensível), confirmado pelo usuário antes do envio.';

create index if not exists nodi_tickets_user_created_idx
  on public.nodi_tickets (user_id, created_at desc);
create index if not exists nodi_tickets_status_idx
  on public.nodi_tickets (status, created_at desc);

alter table public.nodi_tickets enable row level security;

revoke all on public.nodi_tickets from anon, authenticated;
grant select, insert on public.nodi_tickets to authenticated;
grant all on public.nodi_tickets to service_role;

drop policy if exists "nodi_tickets_select_own" on public.nodi_tickets;
create policy "nodi_tickets_select_own"
  on public.nodi_tickets for select
  to authenticated
  using (auth.uid() = user_id);

drop policy if exists "nodi_tickets_insert_own" on public.nodi_tickets;
create policy "nodi_tickets_insert_own"
  on public.nodi_tickets for insert
  to authenticated
  with check (auth.uid() = user_id);

-- ── Telemetria (sem conteúdo sensível) ────────────────────────────────────────

create table if not exists public.nodi_events (
  id         uuid        primary key default gen_random_uuid(),
  user_id    uuid        references auth.users (id) on delete set null,
  -- Nome fechado de evento (whitelist na rota): panel_open, question_asked,
  -- answer_kb, answer_ai, answer_none, problem_flow_started, diagnose_run,
  -- ticket_created, action_clicked, provider_error.
  event      text        not null check (char_length(event) <= 40),
  route      text        check (char_length(route) <= 200),
  module     text        check (char_length(module) <= 40),
  -- Só ids/slugs/números (ex.: kb_entry, confidence, generation_kind).
  -- NUNCA texto livre do usuário — validado na rota antes do insert.
  meta       jsonb       not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

comment on table public.nodi_events is
  'Telemetria do Nodi. Política: nenhum texto livre do usuário — apenas evento + rota + módulo + slugs.';

create index if not exists nodi_events_event_created_idx
  on public.nodi_events (event, created_at desc);

alter table public.nodi_events enable row level security;

revoke all on public.nodi_events from anon, authenticated;
grant all on public.nodi_events to service_role;
